create table PLAYER (
	ID SERIAL PRIMARY KEY,
	USERNAME TEXT UNIQUE,
	PASSWORD TEXT
);

create table TEAM (
	ID SERIAL PRIMARY KEY,
	NAME TEXT,
	CITY TEXT
);

create table GLOBAL_BET (
	ID SERIAL PRIMARY KEY,
	NAME TEXT UNIQUE NOT NULL,
	OWNER_ID SERIAL NOT NULL REFERENCES PLAYER (ID)
);

create table GAME (
	ID SERIAL PRIMARY KEY,
	HOME_TEAM_ID SERIAL NOT NULL REFERENCES TEAM (ID),
	VISITOR_TEAM_ID SERIAL NOT NULL REFERENCES TEAM (ID),
	GLOBAL_BET_ID SERIAL NOT NULL REFERENCES GLOBAL_BET (ID),
	HOME_SCORE SMALLINT,
	VISITOR_SCORE SMALLINT
);

create table LOCAL_BET (
	ID SERIAL PRIMARY KEY,
	PLAYER_ID SERIAL NOT NULL REFERENCES PLAYER (ID),
	GAME_ID SERIAL NOT NULL REFERENCES GAME (ID),
	HOME_SCORE SMALLINT,
	VISITOR_SCORE SMALLINT
);


INSERT INTO TEAM VALUES (1, 'Dynamo', 'Kiev');
INSERT INTO TEAM VALUES (2, 'Dnipro', 'Dnipropetrovsk');
INSERT INTO TEAM VALUES (3, 'Shakhtar', 'Donetsk');
INSERT INTO TEAM VALUES (4, 'Zorya', 'Lugansk');
INSERT INTO TEAM VALUES (5, 'Vorskla', 'Poltava');
INSERT INTO TEAM VALUES (6, 'Oleksandriya', 'Oleksandriya');
INSERT INTO TEAM VALUES (7, 'Karpaty', 'Lviv');
INSERT INTO TEAM VALUES (8, 'Stal', 'Dniprodzerzhynsk');
INSERT INTO TEAM VALUES (9, 'Olimpik', 'Donetsk');
INSERT INTO TEAM VALUES (10, 'Metalist', 'Kharkov');
INSERT INTO TEAM VALUES (11, 'Chernomorets', 'Odessa');
INSERT INTO TEAM VALUES (12, 'Goverla', 'Ushgorod');
INSERT INTO TEAM VALUES (13, 'Metalurg', 'Zaporizhzha');
INSERT INTO TEAM VALUES (14, 'Volyn', 'Lutsk');
